//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPC_MakerSpace_CheckIn.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\decyple")]
        public string class_list_dir_name {
            get {
                return ((string)(this["class_list_dir_name"]));
            }
            set {
                this["class_list_dir_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("class_list_new.dat")]
        public string class_list_filename {
            get {
                return ((string)(this["class_list_filename"]));
            }
            set {
                this["class_list_filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\decyple")]
        public string reasons_list_dir_name {
            get {
                return ((string)(this["reasons_list_dir_name"]));
            }
            set {
                this["reasons_list_dir_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reasons.dat")]
        public string reasons_list_filename {
            get {
                return ((string)(this["reasons_list_filename"]));
            }
            set {
                this["reasons_list_filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\decyple")]
        public string orgs_list_dir_name {
            get {
                return ((string)(this["orgs_list_dir_name"]));
            }
            set {
                this["orgs_list_dir_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("student_orgs.dat")]
        public string orgs_list_filename {
            get {
                return ((string)(this["orgs_list_filename"]));
            }
            set {
                this["orgs_list_filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\decyple\\Documents")]
        public string log_file_dir_name {
            get {
                return ((string)(this["log_file_dir_name"]));
            }
            set {
                this["log_file_dir_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NPC_MakerSpace_Check_In_Out.dat")]
        public string log_file_filename {
            get {
                return ((string)(this["log_file_filename"]));
            }
            set {
                this["log_file_filename"] = value;
            }
        }
    }
}
